<?php
require_once('libs/INIStdPayUtil.php');
$SignatureUtil = new INIStdPayUtil();

$mid 			= "INIpayTest";  								// Merchant ID (INIpayTest should be used for test. MID for production environment will be provided after the agreement for PG usage)
$signKey 		= "SU5JTElURV9UUklQTEVERVNfS0VZU1RS"; 			// Web payment signkey (signkey give here is for test. signkey for production environment will be the same as mid)

$mKey 	= $SignatureUtil->makeHash($signKey, "sha256");

$timestamp 		= $SignatureUtil->getTimestamp();   			// Automatically generated by util
$orderNumber 	= $mid . "_" . $timestamp; 						// Merchant order no (Merchant need to set)
$price 			= "1000";        								// Price(exclude special characters, Merchant need to set)

$params = array(
    "oid" => $orderNumber,
    "price" => $price,
    "timestamp" => $timestamp
);

$sign   = $SignatureUtil->makeSignature($params);
?>
<!DOCTYPE html>
<html lang="ko">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport"
            content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <title>KG Inicis Payment Sample</title>
        <link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/bootstrap.min.css">

		<!--테스트 JS--><script language="javascript" type="text/javascript" src="https://stgstdpay.inicis.com/stdjs/INIStdPay.js" charset="UTF-8"></script>
		<!--운영 JS> <script language="javascript" type="text/javascript" src="https://stdpay.inicis.com/stdjs/INIStdPay.js" charset="UTF-8"></script> -->
        <script type="text/javascript">
            function paybtn() {
                INIStdPay.pay('SendPayForm_id');
            }
        </script>
    </head>

    <body class="wrap">

        <!-- 본문 -->
        <main class="col-8 cont" id="bill-01">
            <!-- Page Title -->
            <section class="mb-5">
                <div class="tit">
                    <h2>Web PC Payment</h2>
                    <p>Call the KG Inicis payment window to provide secure payments through various payment methods.</p>
                </div>
            </section>
            <!-- //Page Title -->


            <!-- Card CONTENTS -->
            <section class="menu_cont mb-5">
                <div class="card">
                    <div class="card_tit">
                        <h3>Web PC Payment</h3>
                    </div>

                    <!-- 유의사항 -->
                    <div class="card_desc">
                        <h4>※ Precaution</h4>
                        <ul>
                            <li>When making a payment with a test MID, it will be approved in real-time, but it will be automatically canceled before midnight (24:00) on the same day.</li>
                        </ul>
                    </div>
                    <!-- //유의사항 -->


                    <form name="" id="SendPayForm_id" method="post" class="mt-5">
                        <div class="row g-3 justify-content-between" style="--bs-gutter-x:0rem;">

                            <!--label class="col-10 col-sm-2 gap-2 input param" style="border:none;">version</label>
                            <label class="col-10 col-sm-9 input"-->
                                <input type="hidden" name="version" value="1.0">
                            <!--/label-->

                            <label class="col-10 col-sm-2 input param" style="border:none;">gopaymethod</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="gopaymethod" value="Card:Directbank:vbank">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">mid</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="mid" value="<?php echo $mid ?>">
                            </label>

                            <label class="col-10 col-sm-2 input param" style="border:none;">oid</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="oid" value="<?php echo $orderNumber ?>">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">price</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="price" value="<?php echo $price ?>">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">timestamp</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="timestamp" value="<?php echo $timestamp ?>">
                            </label>


                            <input type="hidden" name="signature" value="<?php echo $sign ?>">
				    		<input type="hidden" name="mKey" value="<?php echo $mKey ?>">
                            <input type="hidden" name="currency" value="WON">


				    		<label class="col-10 col-sm-2 input param" style="border:none;">goodname</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="goodname" value="테스트상품">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">buyername</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="buyername" value="테스터">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">buyertel</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="buyertel" value="01012345678">
                            </label>

				    		<label class="col-10 col-sm-2 input param" style="border:none;">buyeremail</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="buyeremail" value="test@test.com">
                            </label>

				    		<input type="hidden" name="returnUrl" value="https://{가맹점도메인}/INIstdpay_pc_return.php">
                            <input type="hidden" name="closeUrl" value="https://{가맹점도메인}/close.php">

				    		<label class="col-10 col-sm-2 input param" style="border:none;">acceptmethod</label>
                            <label class="col-10 col-sm-9 input">
                                <input type="text" name="acceptmethod" value="HPP(1):below1000:va_receipt">
                            </label>

                        </div>
                    </form>

				    <button onclick="paybtn()" class="btn_solid_pri col-6 mx-auto btn_lg" style="margin-top:50px">결제 요청</button>

                </div>
            </section>

        </main>

    </body>
</html>
